### ISSUE TITLE
dconf & DBus issues

### ISSUE THREAD

**Issue by jschwartzenberg** [fsquillace/junest#218] opened 2019-03-08 17:09 UTC
When I try to run Evolution I get an endless stream of messages like:
```
(evolution:20044): dconf-WARNING **: 18:06:23.501: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

Maybe I'm doing something wrong or some support is missing or impossible to provide for such applications?

**Comment by fsquillace** [comment] 2019-10-24 20:21
I suspect there is some missing dynamic library and is not related to JuNest itself but it is hard to tell. Consider that by design JuNest comes with very minimal amount of dependencies.

Closing for now.

**Closed by fsquillace** 2019-10-24 20:21 UTC
