### ISSUE TITLE
proot fails when /usr/bin/true is not found

### ISSUE THREAD

**Issue by jonjonw** [fsquillace/junest#85] opened 2015-06-16 05:37 UTC
I build my image on archlinux and I am trying to install on another distro. When I run junest -i junest-x86_64.tar.gz it fails because it cannot find /usr/bin/true. On this system it is located under /bin/true and I do not have access to change it.

I tried setting TRUE=/bin/true in lib.core.sh but I still get the error. Do you have any suggestions?

Here is the output:

```
$ junest -i $HOME/tmp/junest-x86_64.tar.gz 
Installing JuNest from /home/jon/tmp/junest-x86_64.tar.gz...
The default mirror URL is https://mirrors.kernel.org/archlinux/$repo/os/$arch.
Remember to refresh the package databases from the server:
    pacman -Syy
JuNest installed successfully
proot error: execve("/usr/bin/true"): Permission denied
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot-x86_64 --help`.
proot error: can't chmod '/tmp/proot-2030-tKYRic': No such file or directory
proot error: execve("/usr/bin/true"): Permission denied
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot-x86_64 --help`.
proot error: can't chmod '/tmp/proot-2032-emEx0h': No such file or directory
Error: Check if the junest arguments are correct or use the option junest -p "-k 3.10"
```

**Comment by fsquillace** [comment] 2015-06-16 12:41
Hi,

By settings the TRUE to /bin/true it should have worked.

Are you sure the host system uses a 64 bit architecture?
Can you run uname -m? does the /bin/true command works outside junest?

There is the plan to create a fallback mechanism to ensure the executable are found even in different location (https://github.com/fsquillace/junest/issues/79). At this point it would be the first thing to prioritize.

Thanks,
Filippo

**Comment by jonjonw** [comment] 2015-06-16 15:46
The host is 64 bit: uname -m returns x86_64.

I will keep an eye out for #79.

/tmp on the system is mounted as noexec as well. Perhaps that would cause an issue.

Thanks,
Jon

**Comment by fsquillace** [comment] 2015-06-20 15:13
I am taking a look more to your output. It looks that the true command actually exist but it raise a Permission denied:
`proot error: execve("/usr/bin/true"): Permission denied`

I feel that the same problem will happen even with the already built image provided by junest. Can you try that?

Also, the fact that /tmp is mounted as noexec could be the root cause since proot requires to have a prooted executable in /tmp/:
```
$> ll /tmp/prooted-*
-r-x------ 1 feel users 2.1M Jun 20 15:05 /tmp/prooted-15601-9KFO8W
```

Your host system looks quite restricted :/

**Comment by jonjonw** [comment] 2015-06-22 21:14
Thanks @fsquillace 

Yes, it's quite restrictive! I did some digging as well. I think I'll have to wait for the next release of proot which will add support for the PROOT_TMP_DIR environment variable to use an alternate directory.

https://github.com/proot-me/PRoot/commit/cda94e12019170f4553adac2e06510b571576d15

**Comment by fsquillace** [comment] 2015-06-24 18:40
Cool, I am going to close this issue since it looks it is not related specifically to JuNest.

Thanks,
Filippo

**Closed by fsquillace** 2015-06-24 18:40 UTC
